name: Deploy Docker application to Heroku

# On a push to the branch named master
on:
  push:
    branches: 
      - master

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Build and push Docker container to Heroku.
      uses: gonuit/heroku-docker-deploy@v1.3.3 
      with:
        email: sakari.laulajainen@tuni.fi
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: docker-mooc-nodejs
        dockerfile_directory: ./
        dockerfile_name: Dockerfile
        docker_options: "--no-cache"
        process_type: web